<?php
	declare(strict_types=1);
	/** @var FreshRSS_View $this */

$errorMessageHtmlEncoded = htmlspecialchars($this->errorMessage, ENT_NOQUOTES, 'UTF-8');

$reportPreamble = _t('gen.action.report_first_line');
$lineBreakMailto = '%0D%0A';
$reportBody = $reportPreamble . $lineBreakMailto . $this->code . $lineBreakMailto . $errorMessageHtmlEncoded;
?>
<main class="post">
	<div class="alert alert-error">
		<h1 class="alert-head"><?= $this->code ?></h1>
		<p>
			<?= $errorMessageHtmlEncoded ?>
		</p>
		<p>
			<?php if (FreshRSS_Auth::hasAccess()) {?>
			<a href="<?= 'mailto:' . FreshRSS_Context::systemConf()->admin_email . '?subject=error&body=' . $reportBody ?>"><?= _t('gen.action.report_to_admin') ?></a>
			<br />
			<a href="<?= _url('index', 'index') ?>"><?= _t('gen.action.back_to_rss_feeds') ?></a>
			<?php } else { ?>
			<a href="<?= _url('auth', 'login') ?>"><?= _t('gen.auth.login') ?></a>
			<?php } ?>
		</p>
	</div>
</main>
